apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/mysql/0
    server: 192.168.146.199

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/mysql/1
    server: 192.168.146.199

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/mysql/2
    server: 192.168.146.199
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mysql-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
