apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/0
    server: 192.168.146.199

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/1
    server: 192.168.146.199

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/2
    server: 192.168.146.199
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
